//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeObservation) DeepCopyInto(out *AttributeObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeObservation.
func (in *AttributeObservation) DeepCopy() *AttributeObservation {
	if in == nil {
		return nil
	}
	out := new(AttributeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeParameters) DeepCopyInto(out *AttributeParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeParameters.
func (in *AttributeParameters) DeepCopy() *AttributeParameters {
	if in == nil {
		return nil
	}
	out := new(AttributeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientObservation) DeepCopyInto(out *ClientObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientObservation.
func (in *ClientObservation) DeepCopy() *ClientObservation {
	if in == nil {
		return nil
	}
	out := new(ClientObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientParameters) DeepCopyInto(out *ClientParameters) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientParameters.
func (in *ClientParameters) DeepCopy() *ClientParameters {
	if in == nil {
		return nil
	}
	out := new(ClientParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplication) DeepCopyInto(out *KeyHubClientApplication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplication.
func (in *KeyHubClientApplication) DeepCopy() *KeyHubClientApplication {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubClientApplication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplicationList) DeepCopyInto(out *KeyHubClientApplicationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyHubClientApplication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplicationList.
func (in *KeyHubClientApplicationList) DeepCopy() *KeyHubClientApplicationList {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplicationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubClientApplicationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplicationObservation) DeepCopyInto(out *KeyHubClientApplicationObservation) {
	*out = *in
	if in.Binddn != nil {
		in, out := &in.Binddn, &out.Binddn
		*out = new(string)
		**out = **in
	}
	if in.Clientid != nil {
		in, out := &in.Clientid, &out.Clientid
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplicationObservation.
func (in *KeyHubClientApplicationObservation) DeepCopy() *KeyHubClientApplicationObservation {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplicationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplicationParameters) DeepCopyInto(out *KeyHubClientApplicationParameters) {
	*out = *in
	if in.Attribute != nil {
		in, out := &in.Attribute, &out.Attribute
		*out = make([]AttributeParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CallbackURI != nil {
		in, out := &in.CallbackURI, &out.CallbackURI
		*out = new(string)
		**out = **in
	}
	if in.ClientCertificate != nil {
		in, out := &in.ClientCertificate, &out.ClientCertificate
		*out = new(string)
		**out = **in
	}
	if in.Confidential != nil {
		in, out := &in.Confidential, &out.Confidential
		*out = new(bool)
		**out = **in
	}
	if in.IDTokenClaims != nil {
		in, out := &in.IDTokenClaims, &out.IDTokenClaims
		*out = new(string)
		**out = **in
	}
	if in.InitiateLoginURI != nil {
		in, out := &in.InitiateLoginURI, &out.InitiateLoginURI
		*out = new(string)
		**out = **in
	}
	if in.IsServer2Server != nil {
		in, out := &in.IsServer2Server, &out.IsServer2Server
		*out = new(bool)
		**out = **in
	}
	if in.IsSso != nil {
		in, out := &in.IsSso, &out.IsSso
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.MetadataURL != nil {
		in, out := &in.MetadataURL, &out.MetadataURL
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Scopes != nil {
		in, out := &in.Scopes, &out.Scopes
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Segments != nil {
		in, out := &in.Segments, &out.Segments
		*out = new(string)
		**out = **in
	}
	if in.ShowLandingpage != nil {
		in, out := &in.ShowLandingpage, &out.ShowLandingpage
		*out = new(bool)
		**out = **in
	}
	if in.SubjectFormat != nil {
		in, out := &in.SubjectFormat, &out.SubjectFormat
		*out = new(string)
		**out = **in
	}
	if in.TechnicalAdministrator != nil {
		in, out := &in.TechnicalAdministrator, &out.TechnicalAdministrator
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UsedForProvisioning != nil {
		in, out := &in.UsedForProvisioning, &out.UsedForProvisioning
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplicationParameters.
func (in *KeyHubClientApplicationParameters) DeepCopy() *KeyHubClientApplicationParameters {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplicationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplicationSpec) DeepCopyInto(out *KeyHubClientApplicationSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplicationSpec.
func (in *KeyHubClientApplicationSpec) DeepCopy() *KeyHubClientApplicationSpec {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplicationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubClientApplicationStatus) DeepCopyInto(out *KeyHubClientApplicationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubClientApplicationStatus.
func (in *KeyHubClientApplicationStatus) DeepCopy() *KeyHubClientApplicationStatus {
	if in == nil {
		return nil
	}
	out := new(KeyHubClientApplicationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroup) DeepCopyInto(out *KeyHubGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroup.
func (in *KeyHubGroup) DeepCopy() *KeyHubGroup {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupList) DeepCopyInto(out *KeyHubGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyHubGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupList.
func (in *KeyHubGroupList) DeepCopy() *KeyHubGroupList {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupObservation) DeepCopyInto(out *KeyHubGroupObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupObservation.
func (in *KeyHubGroupObservation) DeepCopy() *KeyHubGroupObservation {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystem) DeepCopyInto(out *KeyHubGroupOnSystem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystem.
func (in *KeyHubGroupOnSystem) DeepCopy() *KeyHubGroupOnSystem {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubGroupOnSystem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystemList) DeepCopyInto(out *KeyHubGroupOnSystemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyHubGroupOnSystem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystemList.
func (in *KeyHubGroupOnSystemList) DeepCopy() *KeyHubGroupOnSystemList {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystemList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubGroupOnSystemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystemObservation) DeepCopyInto(out *KeyHubGroupOnSystemObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ShortNameInSystem != nil {
		in, out := &in.ShortNameInSystem, &out.ShortNameInSystem
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystemObservation.
func (in *KeyHubGroupOnSystemObservation) DeepCopy() *KeyHubGroupOnSystemObservation {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystemObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystemParameters) DeepCopyInto(out *KeyHubGroupOnSystemParameters) {
	*out = *in
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.NameInSystem != nil {
		in, out := &in.NameInSystem, &out.NameInSystem
		*out = new(string)
		**out = **in
	}
	if in.Owner != nil {
		in, out := &in.Owner, &out.Owner
		*out = new(string)
		**out = **in
	}
	if in.Provgroup != nil {
		in, out := &in.Provgroup, &out.Provgroup
		*out = make([]ProvgroupParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.System != nil {
		in, out := &in.System, &out.System
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystemParameters.
func (in *KeyHubGroupOnSystemParameters) DeepCopy() *KeyHubGroupOnSystemParameters {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystemParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystemSpec) DeepCopyInto(out *KeyHubGroupOnSystemSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystemSpec.
func (in *KeyHubGroupOnSystemSpec) DeepCopy() *KeyHubGroupOnSystemSpec {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystemSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupOnSystemStatus) DeepCopyInto(out *KeyHubGroupOnSystemStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupOnSystemStatus.
func (in *KeyHubGroupOnSystemStatus) DeepCopy() *KeyHubGroupOnSystemStatus {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupOnSystemStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupParameters) DeepCopyInto(out *KeyHubGroupParameters) {
	*out = *in
	if in.ApplicationAdministration != nil {
		in, out := &in.ApplicationAdministration, &out.ApplicationAdministration
		*out = new(bool)
		**out = **in
	}
	if in.AuditMonths != nil {
		in, out := &in.AuditMonths, &out.AuditMonths
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuditingAuthGroupuuid != nil {
		in, out := &in.AuditingAuthGroupuuid, &out.AuditingAuthGroupuuid
		*out = new(string)
		**out = **in
	}
	if in.Auditor != nil {
		in, out := &in.Auditor, &out.Auditor
		*out = new(bool)
		**out = **in
	}
	if in.Client != nil {
		in, out := &in.Client, &out.Client
		*out = make([]ClientParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ExtendedAccess != nil {
		in, out := &in.ExtendedAccess, &out.ExtendedAccess
		*out = new(string)
		**out = **in
	}
	if in.HideAuditTrail != nil {
		in, out := &in.HideAuditTrail, &out.HideAuditTrail
		*out = new(bool)
		**out = **in
	}
	if in.Member != nil {
		in, out := &in.Member, &out.Member
		*out = make([]MemberParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MembershipAuthGroupuuid != nil {
		in, out := &in.MembershipAuthGroupuuid, &out.MembershipAuthGroupuuid
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PrivateGroup != nil {
		in, out := &in.PrivateGroup, &out.PrivateGroup
		*out = new(bool)
		**out = **in
	}
	if in.ProvisioningAuthGroupuuid != nil {
		in, out := &in.ProvisioningAuthGroupuuid, &out.ProvisioningAuthGroupuuid
		*out = new(string)
		**out = **in
	}
	if in.RecordTrail != nil {
		in, out := &in.RecordTrail, &out.RecordTrail
		*out = new(bool)
		**out = **in
	}
	if in.RotatingPasswordRequired != nil {
		in, out := &in.RotatingPasswordRequired, &out.RotatingPasswordRequired
		*out = new(bool)
		**out = **in
	}
	if in.SingleManaged != nil {
		in, out := &in.SingleManaged, &out.SingleManaged
		*out = new(bool)
		**out = **in
	}
	if in.VaultRecovery != nil {
		in, out := &in.VaultRecovery, &out.VaultRecovery
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupParameters.
func (in *KeyHubGroupParameters) DeepCopy() *KeyHubGroupParameters {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupSpec) DeepCopyInto(out *KeyHubGroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupSpec.
func (in *KeyHubGroupSpec) DeepCopy() *KeyHubGroupSpec {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubGroupStatus) DeepCopyInto(out *KeyHubGroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubGroupStatus.
func (in *KeyHubGroupStatus) DeepCopy() *KeyHubGroupStatus {
	if in == nil {
		return nil
	}
	out := new(KeyHubGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecord) DeepCopyInto(out *KeyHubVaultRecord) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecord.
func (in *KeyHubVaultRecord) DeepCopy() *KeyHubVaultRecord {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubVaultRecord) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecordList) DeepCopyInto(out *KeyHubVaultRecordList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeyHubVaultRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecordList.
func (in *KeyHubVaultRecordList) DeepCopy() *KeyHubVaultRecordList {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecordList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeyHubVaultRecordList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecordObservation) DeepCopyInto(out *KeyHubVaultRecordObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecordObservation.
func (in *KeyHubVaultRecordObservation) DeepCopy() *KeyHubVaultRecordObservation {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecordObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecordParameters) DeepCopyInto(out *KeyHubVaultRecordParameters) {
	*out = *in
	if in.Base64Encoded != nil {
		in, out := &in.Base64Encoded, &out.Base64Encoded
		*out = new(bool)
		**out = **in
	}
	if in.CommentSecretRef != nil {
		in, out := &in.CommentSecretRef, &out.CommentSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.FileSecretRef != nil {
		in, out := &in.FileSecretRef, &out.FileSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.Groupuuid != nil {
		in, out := &in.Groupuuid, &out.Groupuuid
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.TotpSecretRef != nil {
		in, out := &in.TotpSecretRef, &out.TotpSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecordParameters.
func (in *KeyHubVaultRecordParameters) DeepCopy() *KeyHubVaultRecordParameters {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecordParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecordSpec) DeepCopyInto(out *KeyHubVaultRecordSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecordSpec.
func (in *KeyHubVaultRecordSpec) DeepCopy() *KeyHubVaultRecordSpec {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecordSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyHubVaultRecordStatus) DeepCopyInto(out *KeyHubVaultRecordStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyHubVaultRecordStatus.
func (in *KeyHubVaultRecordStatus) DeepCopy() *KeyHubVaultRecordStatus {
	if in == nil {
		return nil
	}
	out := new(KeyHubVaultRecordStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberObservation) DeepCopyInto(out *MemberObservation) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberObservation.
func (in *MemberObservation) DeepCopy() *MemberObservation {
	if in == nil {
		return nil
	}
	out := new(MemberObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemberParameters) DeepCopyInto(out *MemberParameters) {
	*out = *in
	if in.Rights != nil {
		in, out := &in.Rights, &out.Rights
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemberParameters.
func (in *MemberParameters) DeepCopy() *MemberParameters {
	if in == nil {
		return nil
	}
	out := new(MemberParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvgroupObservation) DeepCopyInto(out *ProvgroupObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvgroupObservation.
func (in *ProvgroupObservation) DeepCopy() *ProvgroupObservation {
	if in == nil {
		return nil
	}
	out := new(ProvgroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProvgroupParameters) DeepCopyInto(out *ProvgroupParameters) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Securitylevel != nil {
		in, out := &in.Securitylevel, &out.Securitylevel
		*out = new(string)
		**out = **in
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProvgroupParameters.
func (in *ProvgroupParameters) DeepCopy() *ProvgroupParameters {
	if in == nil {
		return nil
	}
	out := new(ProvgroupParameters)
	in.DeepCopyInto(out)
	return out
}
